#!/bin/bash
 yum install git -y
 git --version
 git config --global user.name "bindusarika"
 git config --global user.email "bindusarika333@gmail.com"
 git config --list
 mkdir cloudinterns
 ll
 cd cloudinterns/
 git init
 git branch -m main
git clone https://github.com/bindusarika/sarika.git
ll
ls -la
